# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-24 05:46
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hood_name', models.CharField(max_length=150)),
            ],
            options={
                'ordering': ['hood_name'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc_name', models.CharField(max_length=255, verbose_name='Pick your Location')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.ImageField(null=True, upload_to='profiles/', verbose_name='Pick Profile Pic')),
                ('profile_id', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(message='ID number must have eight numeric characters', regex='^(\\d{7}|\\d{8})$')], verbose_name='Id Number')),
                ('email_confirmed', models.BooleanField(default=False)),
                ('profile_hood', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hood.Hood')),
                ('profile_owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='hood',
            name='hood_admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hood.Profile'),
        ),
        migrations.AddField(
            model_name='hood',
            name='hood_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hood.Location'),
        ),
    ]
