# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-24 09:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=50)),
                ('business_category', models.CharField(choices=[('B', 'Boutique & Cosmetics Shop'), ('BT', 'Butchery'), ('C', 'Cobblers'), ('E', 'Education'), ('H', 'Hardware'), ('HC', 'HealthCare'), ('K', 'Kiosks'), ('M', 'Supermarkets'), ('V', 'Mpesa Airtel vendors'), ('S', 'Salon')], max_length=2)),
                ('business_description', models.CharField(blank=True, max_length=100, null=True)),
                ('business_email', models.EmailField(max_length=254)),
                ('business_hood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hood.Hood')),
                ('business_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hood.Profile')),
            ],
        ),
    ]
