# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-24 09:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0002_business'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_footage', models.ImageField(blank=True, null=True, upload_to='footages/', verbose_name='Attach Footage')),
                ('news_details', models.TextField()),
                ('news_pub_date', models.DateTimeField(auto_now_add=True)),
                ('news_created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='hood.Profile', verbose_name='Created By')),
                ('news_hood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hood.Hood')),
            ],
            options={
                'verbose_name_plural': 'news',
                'ordering': ['-news_pub_date'],
            },
        ),
    ]
